// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RosquinhaNeguin.Data;

#nullable disable

namespace RosquinhaNeguin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522013522_InicialSQLServer")]
    partial class InicialSQLServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RosquinhaNeguin.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmojiProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Categoria = "churros",
                            Descricao = "Crocante por fora, macio por dentro",
                            Emoji = "🍩",
                            Nome = "Churros Tradicional",
                            Preco = 8m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Categoria = "churros",
                            Descricao = "Recheado com doce de leite cremoso",
                            Emoji = "🍮",
                            Nome = "Churros Doce de Leite",
                            Preco = 10m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Categoria = "churros",
                            Descricao = "Recheio de chocolate belga",
                            Emoji = "🍫",
                            Nome = "Churros Chocolate",
                            Preco = 10m
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Categoria = "churros",
                            Descricao = "Generoso recheio de Nutella",
                            Emoji = "🌰",
                            Nome = "Churros Nutella",
                            Preco = 15m
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Categoria = "churros",
                            Descricao = "Cremoso e irresistível",
                            Emoji = "🥛",
                            Nome = "Churros Leite Ninho",
                            Preco = 15m
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Categoria = "churros",
                            Descricao = "Geleia artesanal de morango",
                            Emoji = "🍓",
                            Nome = "Churros Morango",
                            Preco = 14m
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Categoria = "rosquinhas",
                            Descricao = "Receita original da casa",
                            Emoji = "🍩",
                            Nome = "Rosquinha Tradicional",
                            Preco = 5m
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Categoria = "rosquinhas",
                            Descricao = "Com cobertura de chocolate",
                            Emoji = "🍫",
                            Nome = "Rosquinha Chocolate",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Categoria = "rosquinhas",
                            Descricao = "Recheada e coberta",
                            Emoji = "🍮",
                            Nome = "Rosquinha Doce de Leite",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Categoria = "rosquinhas",
                            Descricao = "Premium e indulgente",
                            Emoji = "🌰",
                            Nome = "Rosquinha Nutella",
                            Preco = 8m
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Categoria = "rosquinhas",
                            Descricao = "Leite em pó Ninho cremoso",
                            Emoji = "🥛",
                            Nome = "Rosquinha Ninho",
                            Preco = 8m
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Categoria = "rosquinhas",
                            Descricao = "Fresco e delicado",
                            Emoji = "🍓",
                            Nome = "Rosquinha Morango",
                            Preco = 8m
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            Categoria = "salgados",
                            Descricao = "Frango desfiado temperado",
                            Emoji = "🍗",
                            Nome = "Coxinha",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            Categoria = "salgados",
                            Descricao = "Massa fina e recheio especial",
                            Emoji = "🥟",
                            Nome = "Risole",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            Categoria = "salgados",
                            Descricao = "Massa amanteigada artesanal",
                            Emoji = "🥧",
                            Nome = "Empada",
                            Preco = 7m
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            Categoria = "salgados",
                            Descricao = "Aberta, no estilo árabe",
                            Emoji = "🫓",
                            Nome = "Esfiha",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            Categoria = "salgados",
                            Descricao = "Quentinho e puxento",
                            Emoji = "🧀",
                            Nome = "Pão de Queijo",
                            Preco = 5m
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            Categoria = "bebidas",
                            Descricao = "Grãos selecionados",
                            Emoji = "☕",
                            Nome = "Café",
                            Preco = 4m
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            Categoria = "bebidas",
                            Descricao = "Cremoso e reconfortante",
                            Emoji = "🥛",
                            Nome = "Café com Leite",
                            Preco = 5m
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            Categoria = "bebidas",
                            Descricao = "Gelado e refrescante",
                            Emoji = "🥤",
                            Nome = "Refrigerante",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            Categoria = "bebidas",
                            Descricao = "Frutas frescas da estação",
                            Emoji = "🍊",
                            Nome = "Suco Natural",
                            Preco = 7m
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            Categoria = "bebidas",
                            Descricao = "Com ou sem gás",
                            Emoji = "💧",
                            Nome = "Água Mineral",
                            Preco = 3m
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "3 Churros Tradicionais",
                            Emoji = "🍩",
                            Nome = "Combo 3 Churros",
                            Preco = 25m
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "5 Churros Tradicionais",
                            Emoji = "🍩",
                            Nome = "Combo 5 Churros",
                            Preco = 40m
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "10 Churros",
                            Emoji = "👨‍👩‍👧‍👦",
                            Nome = "Combo Família",
                            Preco = 70m
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "2 Churros + 2 Rosquinhas",
                            Emoji = "💑",
                            Nome = "Combo Casal",
                            Preco = 22m
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "2 Rosquinhas + Café",
                            Emoji = "☕",
                            Nome = "Combo Café da Tarde",
                            Preco = 12m
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "1 Churros + 1 Donut",
                            Emoji = "🍬",
                            Nome = "Combo Doce",
                            Preco = 16m
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "15 Mini Churros",
                            Emoji = "🎉",
                            Nome = "Combo Festa",
                            Preco = 60m
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "4 Churros + 4 Rosquinhas",
                            Emoji = "👯",
                            Nome = "Combo Amigos",
                            Preco = 35m
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "Salgado + Rosquinha + Refri",
                            Emoji = "🥙",
                            Nome = "Combo Lanche",
                            Preco = 18m
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            Categoria = "combos",
                            Descricao = "2 Churros + 2 Salgados + 2 Bebidas",
                            Emoji = "⭐",
                            Nome = "Combo Completo",
                            Preco = 30m
                        });
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.ItemPedido", b =>
                {
                    b.HasOne("RosquinhaNeguin.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RosquinhaNeguin.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
