// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RosquinhaNeguin.Data;

#nullable disable

namespace RosquinhaNeguin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RosquinhaNeguin.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "churros"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "rosquinhas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "salgados"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "bebidas"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "combos"
                        });
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmojiProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.LogLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsLogin");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Nome");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CategoriaId = 1,
                            Descricao = "Crocante por fora, macio por dentro",
                            Emoji = "🍩",
                            Estoque = 50,
                            Nome = "Churros Tradicional",
                            Preco = 8m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CategoriaId = 1,
                            Descricao = "Recheado com doce de leite cremoso",
                            Emoji = "🍮",
                            Estoque = 50,
                            Nome = "Churros Doce de Leite",
                            Preco = 10m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CategoriaId = 1,
                            Descricao = "Recheio de chocolate belga",
                            Emoji = "🍫",
                            Estoque = 50,
                            Nome = "Churros Chocolate",
                            Preco = 10m
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CategoriaId = 1,
                            Descricao = "Generoso recheio de Nutella",
                            Emoji = "🌰",
                            Estoque = 50,
                            Nome = "Churros Nutella",
                            Preco = 15m
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CategoriaId = 1,
                            Descricao = "Cremoso e irresistível",
                            Emoji = "🥛",
                            Estoque = 50,
                            Nome = "Churros Leite Ninho",
                            Preco = 15m
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CategoriaId = 1,
                            Descricao = "Geleia artesanal de morango",
                            Emoji = "🍓",
                            Estoque = 50,
                            Nome = "Churros Morango",
                            Preco = 14m
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CategoriaId = 2,
                            Descricao = "Receita original da casa",
                            Emoji = "🍩",
                            Estoque = 50,
                            Nome = "Rosquinha Tradicional",
                            Preco = 5m
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CategoriaId = 2,
                            Descricao = "Com cobertura de chocolate",
                            Emoji = "🍫",
                            Estoque = 50,
                            Nome = "Rosquinha Chocolate",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CategoriaId = 2,
                            Descricao = "Recheada e coberta",
                            Emoji = "🍮",
                            Estoque = 50,
                            Nome = "Rosquinha Doce de Leite",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CategoriaId = 2,
                            Descricao = "Premium e indulgente",
                            Emoji = "🌰",
                            Estoque = 50,
                            Nome = "Rosquinha Nutella",
                            Preco = 8m
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            CategoriaId = 2,
                            Descricao = "Leite em pó Ninho cremoso",
                            Emoji = "🥛",
                            Estoque = 50,
                            Nome = "Rosquinha Ninho",
                            Preco = 8m
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            CategoriaId = 2,
                            Descricao = "Fresco e delicado",
                            Emoji = "🍓",
                            Estoque = 50,
                            Nome = "Rosquinha Morango",
                            Preco = 8m
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            CategoriaId = 3,
                            Descricao = "Frango desfiado temperado",
                            Emoji = "🍗",
                            Estoque = 50,
                            Nome = "Coxinha",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            CategoriaId = 3,
                            Descricao = "Massa fina e recheio especial",
                            Emoji = "🥟",
                            Estoque = 50,
                            Nome = "Risole",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            CategoriaId = 3,
                            Descricao = "Massa amanteigada artesanal",
                            Emoji = "🥧",
                            Estoque = 50,
                            Nome = "Empada",
                            Preco = 7m
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            CategoriaId = 3,
                            Descricao = "Aberta, no estilo árabe",
                            Emoji = "🫓",
                            Estoque = 50,
                            Nome = "Esfiha",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            CategoriaId = 3,
                            Descricao = "Quentinho e puxento",
                            Emoji = "🧀",
                            Estoque = 50,
                            Nome = "Pão de Queijo",
                            Preco = 5m
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            CategoriaId = 4,
                            Descricao = "Grãos selecionados",
                            Emoji = "☕",
                            Estoque = 50,
                            Nome = "Café",
                            Preco = 4m
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            CategoriaId = 4,
                            Descricao = "Cremoso e reconfortante",
                            Emoji = "🥛",
                            Estoque = 50,
                            Nome = "Café com Leite",
                            Preco = 5m
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            CategoriaId = 4,
                            Descricao = "Gelado e refrescante",
                            Emoji = "🥤",
                            Estoque = 50,
                            Nome = "Refrigerante",
                            Preco = 6m
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            CategoriaId = 4,
                            Descricao = "Frutas frescas da estação",
                            Emoji = "🍊",
                            Estoque = 50,
                            Nome = "Suco Natural",
                            Preco = 7m
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            CategoriaId = 4,
                            Descricao = "Com ou sem gás",
                            Emoji = "💧",
                            Estoque = 50,
                            Nome = "Água Mineral",
                            Preco = 3m
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "3 Churros Tradicionais",
                            Emoji = "🍩",
                            Estoque = 50,
                            Nome = "Combo 3 Churros",
                            Preco = 25m
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "5 Churros Tradicionais",
                            Emoji = "🍩",
                            Estoque = 50,
                            Nome = "Combo 5 Churros",
                            Preco = 40m
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "10 Churros",
                            Emoji = "👨‍👩‍👧‍👦",
                            Estoque = 50,
                            Nome = "Combo Família",
                            Preco = 70m
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "2 Churros + 2 Rosquinhas",
                            Emoji = "💑",
                            Estoque = 50,
                            Nome = "Combo Casal",
                            Preco = 22m
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "2 Rosquinhas + Café",
                            Emoji = "☕",
                            Estoque = 50,
                            Nome = "Combo Café da Tarde",
                            Preco = 12m
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "1 Churros + 1 Donut",
                            Emoji = "🍬",
                            Estoque = 50,
                            Nome = "Combo Doce",
                            Preco = 16m
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "15 Mini Churros",
                            Emoji = "🎉",
                            Estoque = 50,
                            Nome = "Combo Festa",
                            Preco = 60m
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "4 Churros + 4 Rosquinhas",
                            Emoji = "👯",
                            Estoque = 50,
                            Nome = "Combo Amigos",
                            Preco = 35m
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "Salgado + Rosquinha + Refri",
                            Emoji = "🥙",
                            Estoque = 50,
                            Nome = "Combo Lanche",
                            Preco = 18m
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            CategoriaId = 5,
                            Descricao = "2 Churros + 2 Salgados + 2 Bebidas",
                            Emoji = "⭐",
                            Estoque = 50,
                            Nome = "Combo Completo",
                            Preco = 30m
                        });
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.ItemPedido", b =>
                {
                    b.HasOne("RosquinhaNeguin.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RosquinhaNeguin.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.LogLogin", b =>
                {
                    b.HasOne("RosquinhaNeguin.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("RosquinhaNeguin.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.Produto", b =>
                {
                    b.HasOne("RosquinhaNeguin.Models.Categoria", "CategoriaObjeto")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaObjeto");
                });

            modelBuilder.Entity("RosquinhaNeguin.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
